[package]
name = "bin"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.3", features = ["derive"] }
dotenv = "0.15.0"
ethers-providers = "1.0"
itertools = "0.10.5"
log = "0.4"
log4rs = { version = "1.2.0", default_features = false, features = ["console_appender", "file_appender"] }
rand = "0.8"
rand_xorshift = "0.3"
reqwest = { version = "0.11", default-features = false, features = [ "json", "rustls-tls" ] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.66"
tokio = { version = "1", features = ["full"] }
types = { path = "../types" }
prover = { path = "../prover" }

[[bin]]
name = "setup"
path = "src/setup.rs"

[[bin]]
name = "prove"
path = "src/prove.rs"

[[bin]]
name = "verify"
path = "src/verify.rs"

[[bin]]
name = "mock_testnet"
path = "src/mock_testnet.rs"
