[package]
name = "bin"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ethers-providers.workspace = true
itertools.workspace = true
log.workspace = true
log4rs.workspace = true
rand.workspace = true
rand_xorshift.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
tokio.workspace = true

prover.workspace = true
integration.workspace = true

[[bin]]
name = "zkevm_prove"
path = "src/zkevm_prove.rs"

[[bin]]
name = "zkevm_verify"
path = "src/zkevm_verify.rs"

[[bin]]
name = "mock_testnet"
path = "src/mock_testnet.rs"

[features]
default = []
inner-prove = ["prover/test"]
chunk-prove = ["prover/test"]
batch-prove = ["chunk-prove"]
