[package]
name = "bin"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.3", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.10.0"
ethers-providers = "1.0"
itertools = "0.10.5"
halo2_proofs = { git = "https://github.com/scroll-tech/halo2.git", branch = "develop"}
log = "0.4"
log4rs = { version = "1.2.0", default_features = false, features = ["console_appender", "file_appender"] }
rand = "0.8"
rand_xorshift = "0.3"
reqwest = { version = "0.11", default-features = false, features = [ "json", "rustls-tls" ] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.66"
tiny-keccak = "2.0.2"
tokio = { version = "1", features = ["full"] }
integration = { path = "../integration" }
# udpate me once 
# https://github.com/scroll-tech/zkevm-circuits/pull/944 
# https://github.com/scroll-tech/halo2/pull/67
# are merged
prover = { git = "https://github.com/scroll-tech/zkevm-circuits.git", branch = "re-randomize-srs", default-features = false, features = ["parallel_syn", "scroll", "shanghai"] }

[[bin]]
name = "zkevm_prove"
path = "src/zkevm_prove.rs"

[[bin]]
name = "zkevm_verify"
path = "src/zkevm_verify.rs"

[[bin]]
name = "mock_testnet"
path = "src/mock_testnet.rs"

[[bin]]
name = "rerandomize_srs"
path = "src/re_rand_srs.rs"