[package]
name = "bin"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.3", features = ["derive"] }
dotenv = "0.15.0"
ethers-providers = "1.0"
itertools = "0.10.5"
log = "0.4"
log4rs = { version = "1.2.0", default_features = false, features = ["console_appender", "file_appender"] }
rand = "0.8"
rand_xorshift = "0.3"
reqwest = { version = "0.11", default-features = false, features = [ "json", "rustls-tls" ] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.66"
tokio = { version = "1", features = ["full"] }
integration = { path = "../integration" }
prover = { git = "https://github.com/scroll-tech/zkevm-circuits.git", branch = "develop", default-features = false, features = ["parallel_syn", "scroll", "shanghai"] }

[[bin]]
name = "zkevm_prove"
path = "src/zkevm_prove.rs"

[[bin]]
name = "zkevm_verify"
path = "src/zkevm_verify.rs"

[[bin]]
name = "mock_testnet"
path = "src/mock_testnet.rs"

[features]
default = []
inner-prove = ["prover/test"]
chunk-prove = ["prover/test"]
batch-prove = ["chunk-prove"]
