[package]
name = "integration"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
glob.workspace = true
itertools.workspace = true
log.workspace = true
log4rs.workspace = true
rand.workspace = true
serde.workspace = true
serde_derive.workspace = true

halo2_proofs.workspace = true
prover.workspace = true
zkevm-circuits.workspace = true

[features]
default = ["prove_verify"]
prove_verify = []
